spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    hikari:
      pool-name: jdbc/Postgres
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 60000
      auto-commit: true
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id.new_generator_mappings: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: hotel-search-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    properties:
      spring:
        json:
          value:
            default:
              type: com.hotel.booking.domain.model.SearchEvent
          trusted:
            packages: "com.hotel.booking.domain.model"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
